### ISSUE TITLE
关于您提供的预训练模型在中文测试集上的泛化性能

### ISSUE THREAD

**Issue by qingfusheng** [csun22/Synthetic-Voice-Detection-Vocoder-Artifacts#11]
您好，很抱歉打扰到您，我想问一下您关于您提供的预训练模型在中文数据集的泛化性能，以及DEEPFAKE-O-METER系统中其他模型的性能。因为我在本地测试中文的TTS用例时效果不是很好，以及那种英腔的中文测试用例会被检测为真的问题。谢谢您。

**Comment by qingfusheng** [comment]
在对您的方法进行测试后发现，针对于中文的数据集，您的方法总是会将假的检测为真的。然后我还测试了结合whisper的那个方法，它倾向于将中文认定为假的，英文认定为真的。这是为什么呢？

**Comment by csun22** [comment]
Hi,

Thanks for your question. We have not done any re-training on those methods you mentioned on our DEEPFAKE-O-METER system, and I am sure the author of those methods will be willing to help you with your questions. 

For the Chinese context, since all the audio methods we have pre-trained are **not trained** on the Chinese dataset, you might need to do some re-train process by yourself to increase the accuracy of the models. 

Please let me know if you have any other questions.
